name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
   # container: Ubuntu:16.04
    steps:
    - uses: actions/checkout@v1
   # - name: Install python
    #  run: apt-get update && apt-get install python3 python3-devel python3-pip
    - name: Install setuptools
      run: pip3 install -U pip setuptools
    - name: Install ue-4docker
      run: pip3 install ue4-docker
   # - name: Configure firewall
    #  run: ue4-docker setup
    - name: Build Image
      run: ue4-docker build 4.21.1 --noengine
