name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GIT_USERNAME: ${{ secrets.UE4DOCKER_USERNAME }}
      GIT_PASSWORD: ${{ secrets.UE4DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: Git credential
      run: git config credential.helper '!f() {sleep 1; echo "username=${GIT_USERNAME}";echo "password=${GIT_PASSWORD}";};'
    - name: Pull UE4 source
      run: git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/EpicGames/UnrealEngine.git
    - name: Setup
      run: |
        cd UnrealEngine
        ./Setup.sh
        ./GenerateProjectFiles.sh
    - name: Make
      run: make
    - name: CD back
      run: cd ..
    






    # - uses: actions/setup-python@v1
    # - name: Install setuptools
    #   run: pip3 install -U setuptools
    # - name: Install ue4-docker
    #   run: pip3 install ue4-docker
    # - name: Setup ue4-docker
    #   run: ue4-docker setup
    # - name: Build Image
    #   run: ue4-docker build 4.21.1 --no-engine
